{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "> import time \\# Import the time module for adding delay import random  \n",
    "> import pandas as pd  \n",
    "> from together import Together\n",
    "\n",
    "\\# Define API key and initialize client  \n",
    "TOGETHER_API_KEY =  \n",
    "\"90c790f822552c8d116f7f93ecce1316a27ab4b147b597485ca0aafd825eda71\"\n",
    "client = Together(api_key=TOGETHER_API_KEY)\n",
    "\n",
    "> \\# Define the lists and dictionary  \n",
    "> names = \\[  \n",
    "> \"Aarav\", \"Vivaan\", \"Aditya\", \"Ananya\", \"Diya\", \"Rohan\", \"Ishita\",\n",
    "> \"Aryan\", \"Riya\", \"Kavya\", \"Arjun\", \"Saanvi\", \"Lakshay\", \"Prisha\",\n",
    "> \"Meera\", \"Kabir\", \"Nidhi\", \"Vihaan\", \"Avni\", \"Tanvi\", \"Kunal\",\n",
    "> \"Siddharth\", \"Divya\", \"Sneha\", \"Harsh\", \"Akshay\", \"Isha\", \"Ritik\",\n",
    "> \"Nisha\", \"Rahul\", \"Krishna\", \"Pooja\", \"Anjali\", \"Vikram\", \"Shruti\",\n",
    "> \"Aisha\", \"Yash\", \"Neha\", \"Jay\", \"Gauri\",  \n",
    "> \"Karthik\", \"Tanya\", \"Sakshi\", \"Manav\", \"Radhika\", \"Tushar\", \"Payal\",\n",
    "> \"Raj\", \"Simran\", \"Preeti\"  \n",
    "> \\]\n",
    ">\n",
    "> surnames = \\[  \n",
    "> \"Sharma\", \"Verma\", \"Gupta\", \"Jain\", \"Singh\",  \n",
    "> \"Yadav\", \"Chauhan\", \"Kumar\", \"Mishra\", \"Tripathi\",  \n",
    "> \"Pandey\", \"Dubey\", \"Tiwari\", \"Pathak\", \"Shukla\",  \n",
    "> \"Reddy\", \"Naidu\", \"Rao\", \"Patel\", \"Desai\",  \n",
    "> \"Joshi\", \"Mehta\", \"Iyer\", \"Nair\", \"Pillai\",  \n",
    "> \"Shetty\", \"Ghosh\", \"Mukherjee\", \"Chatterjee\", \"Banerjee\", \"Das\",\n",
    "> \"Sen\", \"Basu\", \"Roy\", \"Bhattacharya\",  \n",
    "> \"Chowdhury\", \"Gowda\", \"Menon\", \"Kulkarni\", \"Chavan\", \"Patil\",\n",
    "> \"Sawant\", \"Thakur\", \"Bhandari\", \"Rastogi\", \"Agarwal\", \"Malhotra\",\n",
    "> \"Kapoor\", \"Chopra\", \"Arora\"  \n",
    "> \\]\n",
    "\n",
    "jobs_with_skills = {  \n",
    "\"Software Developer\": \\[\"Java\", \"Python\", \"C++\", \"Git\", \"SDLC\"\\],  \n",
    "\"Data Scientist\": \\[\"Data analysis\", \"Python\", \"R\", \"Tableau\", \"Big\n",
    "data\"\\],  \n",
    "\"Cloud Architect\": \\[\"AWS\", \"Azure\", \"GCP\", \"Kubernetes\",\n",
    "\"Networking\"\\], \"DevOps Engineer\": \\[\"CI/CD\", \"Docker\", \"Monitoring\n",
    "tools\", \"Version control\"\\],  \n",
    "\"Cybersecurity Analyst\": \\[\"Network security\", \"Ethical hacking\", \"Risk\n",
    "management\"\\],  \n",
    "\"Business Analyst\": \\[\"Requirement analysis\", \"Documentation\",\n",
    "\"Problem-solving\"\\],  \n",
    "\"AI/ML Engineer\": \\[\"TensorFlow\", \"PyTorch\", \"NLP\", \"Model\n",
    "deployment\"\\], \"Database Administrator (DBA)\": \\[\"MySQL\", \"PostgreSQL\",\n",
    "\"SQL  \n",
    "scripting\"\\],  \n",
    "\"UI/UX Designer\": \\[\"Wireframing\", \"Prototyping\", \"User research\"\\], \"IT\n",
    "Project Manager\": \\[\"Agile\", \"Scrum\", \"Risk assessment\", \"Budgeting\"\\] }\n",
    "\n",
    "> reasons_for_selection = \\[  \n",
    "> \"Strong technical skills relevant to the role.\",  \n",
    "> \"Extensive experience in a similar position.\",  \n",
    "> \"Positive attitude and enthusiasm for the role.\",  \n",
    "> \"Exceptional performance during the interview process.\", \"Relevant\n",
    "> certifications or educational background.\" \\]\n",
    ">\n",
    "> reasons_for_rejection = \\[  \n",
    "> \"Lack of relevant experience for the role.\",  \n",
    "> \"Inadequate technical skills or certifications.\", \"Poor performance\n",
    "> during the interview.\",  \n",
    "> \"Mismatch between applicant's and company's values.\", \"Unrealistic\n",
    "> salary expectations.\"  \n",
    "> \\]\n",
    ">\n",
    "> performances = \\[\"Selected\", \"Rejected\"\\]\n",
    ">\n",
    "> \\# Create DataFrame  \n",
    "> data = \\[\\]\n",
    ">\n",
    "> for i in range(10): \\# Adjust the range for the number of candidates\n",
    "> name = random.choice(names)  \n",
    "> surname = random.choice(surnames)  \n",
    "> role = random.choice(list(jobs_with_skills.keys()))\n",
    "\n",
    "\\# Generate transcript prompt  \n",
    "transcript_prompt = f\"Generate a transcript of an interview for the role\n",
    "of {role} with candidate {name} {surname}.\"  \n",
    "response = client.chat.completions.create(  \n",
    "model=\"meta-llama/Llama-Vision-Free\",  \n",
    "messages=\\[{\"role\": \"user\", \"content\": transcript_prompt}\\]  \n",
    ")  \n",
    "transcript = response.choices\\[0\\].message.content\n",
    "\n",
    "\\# Generate candidate profile prompt  \n",
    "profile_prompt = f\"Generate a professional candidate profile for {name}\n",
    "{surname} applying for the role of {role}.\"  \n",
    "response_profile = client.chat.completions.create(  \n",
    "model=\"meta-llama/Llama-Vision-Free\",  \n",
    "messages=\\[{\"role\": \"user\", \"content\": profile_prompt}\\]  \n",
    ")  \n",
    "profile = response_profile.choices\\[0\\].message.content\n",
    "\n",
    "performance = random.choice(performances)  \n",
    "reason = random.choice(reasons_for_selection if performance ==\n",
    "\"Selected\" else reasons_for_rejection)\n",
    "\n",
    "> \\# Add to the data  \n",
    "> data.append({  \n",
    "> \"Name\": name,  \n",
    "> \"Surname\": surname,  \n",
    "> \"Role\": role,  \n",
    "> \"Transcript\": transcript,  \n",
    "> \"Candidate Profile\": profile,  \n",
    "> \"Performance\": performance,  \n",
    "> \"Reason\": reason  \n",
    "> })\n",
    ">\n",
    "> \\# Create DataFrame and save it  \n",
    "> df = pd.DataFrame(data)  \n",
    "> print(df)  \n",
    "> df.to_excel(\"infy_Assignment.xlsx\", index=False)\n",
    ">\n",
    "> Name Surname Role \\\\ 0 Neha Jain Software Developer 1 Aisha Shetty\n",
    "> DevOps Engineer 2 Ananya Chavan Cybersecurity Analyst 3 Aryan Mehta\n",
    "> AI/ML Engineer 4 Siddharth Sen Data Scientist 5 Sakshi Bhandari\n",
    "> Database Administrator (DBA)\n",
    ">\n",
    "> 6 Payal Malhotra DevOps Engineer 7 Riya Mishra DevOps Engineer 8\n",
    "> Radhika Pillai DevOps Engineer 9 Kavya Mehta Data Scientist\n",
    ">\n",
    "> Transcript \\\\ 0 Here is a transcript of an interview for the r... 1\n",
    "> Here is a transcript of an interview for the r... 2 Here is a\n",
    "> transcript of an interview for the r... 3 Here is a transcript of an\n",
    "> interview for the r... 4 Here is a transcript of an interview for the\n",
    "> r... 5 Here is a transcript of an interview for the r... 6 Here is a\n",
    "> transcript of an interview for the r... 7 Here is a transcript of an\n",
    "> interview for the r... 8 Here is a transcript of an interview for the\n",
    "> r... 9 Here is a transcript of an interview for the r...\n",
    ">\n",
    "> Candidate Profile Performance \\\\ 0 Here's a sample professional\n",
    "> candidate profile... Rejected 1 Here's a professional candidate\n",
    "> profile for Ai... Rejected 2 Here's a professional candidate profile\n",
    "> for An... Rejected 3 Here's a professional candidate profile for Ar...\n",
    "> Rejected 4 Here's a professional candidate profile for Si... Selected\n",
    "> 5 Here's a professional candidate profile for Sa... Rejected 6 Here is\n",
    "> a professional candidate profile for P... Rejected 7 Here's a\n",
    "> professional candidate profile for Ri... Selected 8 Here's a\n",
    "> professional candidate profile for Ra... Rejected 9 Here's a\n",
    "> professional candidate profile for Ka... Selected\n",
    ">\n",
    "> Reason 0 Mismatch between applicant's and company's val... 1\n",
    "> Inadequate technical skills or certifications. 2 Lack of relevant\n",
    "> experience for the role. 3 Inadequate technical skills or\n",
    "> certifications. 4 Extensive experience in a similar position. 5\n",
    "> Mismatch between applicant's and company's val... 6 Lack of relevant\n",
    "> experience for the role. 7 Extensive experience in a similar position.\n",
    "> 8 Lack of relevant experience for the role. 9 Extensive experience in\n",
    "> a similar position."
   ],
   "id": "42a14256-91c8-446e-92a7-ab6bf11055d3"
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {}
}
